CREATE TABLE "public"."User" (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) DEFAULT '' NOT NULL
);

CREATE TABLE "public"."Journey"(
    id SERIAL PRIMARY KEY NOT NULL,
    jumpingOff VARCHAR(255) NOT NULL,
    destination VARCHAR(255) NOT NULL,
    inputTime VARCHAR(255) NOT NULL DEFAULT date(now()),
    outputTime VARCHAR(255) NOT NULL
)